DJANGOSITE/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('invites/', include('invites.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

invites/urls.py
from django.urls import path
from .views import *
urlpatterns = [

    path('', Invites.as_view(), name='invites'),
    path('web/', CreateInvites.as_view(), name='add_invites'),
    path('web/<int:pk>/', ViewInvites.as_view(), name='view_invites'),
    # path('web/<int:invites_id>/', view_invites, name='view_invites'),
]

news/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='user_logout'),
    path('test/', test, name='test'),
    path('', HomeNews.as_view(), name='home'),
    # path('category/<int:category_id>/', get_category, name='category'),
    path('category/<int:category_id>/', NewsbyCategory.as_view(), name='category'),
    path('news/<int:pk>/', ViewNews.as_view(), name='view_news'),
    # path('news/<int:news_id>/', view_news, name='view_news'),
    # path('news/add-news/', add_news, name='add_news'),
    path('news/add-news/', CreateNews.as_view(), name='add_news'),
]

invites/models.py
from django.db import models
from django.urls import reverse

class Invites(models.Model):
    name = models.CharField(max_length=150, verbose_name= 'ФИО')
    comment = models.TextField(blank=True, verbose_name='Коммент')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Редактировано')
    is_confirm = models.BooleanField(default=False, verbose_name='Подтверждения!')
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('view_invites', kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Web-приглосительное'
        verbose_name_plural = 'Пригласительные'
        ordering = ['-created_at']

invites/forms.py
from django import forms
from .models import Invites


class InvitesForm(forms.ModelForm):
    class Meta:
        model = Invites
        #fields = '__all__'
        fields = ['name', 'comment', 'is_confirm']
        choices = ((True, 'Обязательно буду!'), (False, 'К сожалению, не смогу ...'),)
        widgets = {
             'name': forms.TextInput(attrs={'class': 'form-control'}),
             'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
             'is_confirm': forms.RadioSelect(attrs={'class': 'form-check-input', 'name':'rating'}, choices=choices),
        }

invites/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView
from .forms import InvitesForm
from invites.models import Invites
from .models import Invites as InvitesModel


# def index(request):
#     return render(request, 'invites/add_invites.html', {'title': 'Web-пригласительное'})

class Invites(ListView):
    model = Invites
    template_name = 'invites/main.html'
    context_object_name = 'invites'

class ViewInvites(DetailView):
    model = InvitesModel
    context_object_name = 'invites_item'
    template_name = 'invites/invites_detail.html'

# def view_invites(request, invites_id):
#     invites_item = get_object_or_404(InvitesModel, pk=invites_id)
#     # invites_item = InvitesModel.objects.get(pk=invites_id)
#     return render(request, 'invites/invites_detail.html', {"invites_item": invites_item })
class CreateInvites(CreateView):
    form_class = InvitesForm
    template_name = 'invites/add_invites.html'
    raise_exception = True

invites/templates/invites/add_invites.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
  <body>

      <div id="headerwrap">
           <div class="container">
               <div class="row">
                <div class="col-lg col-md col-sm "id="img">
                    <img src="/static/img/mainphoto.jpg" alt="Наше фото">
                </div>
                <div class="col-lg col-md col-sm" id = "textmain">
                    <div class="col-lg col-md col-sm" id = "names">
                    <h1 id = "woman"> Екатерина </h1>
                         <h4 id="and"> и </h4>
                    <h1 id = "men"> Марк </h1>
                </div>
                    <div class="col-lg col-md col-sm" id = "data1">
                        <h4> 17 </h4>
                        <h4> Сентябрь </h4>
                        <h4> 2022</h4>
                    </div>
                    <div id="time">
                        <h4> 14:00 </h4>
                    </div>
                </div>
               </div>
            </div>
      </div>

      <div class = "main">
       <div class="container">
           <div id="data2">
               <h3 > До события </h3>
                <div class="col-sm col-md col-lg" >
                    <script src="//megatimer.ru/get/ae53098c249859ee838a37668d235d7b.js"></script>
                </div>
           </div>
    </div>
    <div class = "box">
       <div id="info">
           <h3>Место проведения</h3>
           <div class="maps row">
               <div id="map" style="width: 700px; height: 400px"></div>
                <p> Парк "Сатал", Летняя веранда
г. Якутск, Маганский тракт, 6 км.</p>
           </div>

            <h3>Наши пожелания</h3>
            <p> Мы очень старались сделать праздник красивым и будем рады!</p>
                <p>Не ломайте голову над подарками: </p>
                <p>Ваши пожелания в конвертах помогут нам осуществить мечту </p>
                    <p>Спасибо!</p>
       </div>
   </div>
          <h3>Подтвердите свое присутствие:</h3>
  </div>

  <div class="f" >
      <div class = "card col-lg-6 col-md-8 col-sm-8">
          <div class="card-body">
            <form action="{% url 'add_invites' %}" method="post">
                  {% csrf_token %}
                <label id = "name"> Ваше Имя</label>
                <div class = "mb-3"><input name = "name" required id="id_name" class="form-control"> </div>
                <label id = "questionid"> Придете ли Вы на наш вечер?</label>

                    {% for item in form.is_confirm %}
                <div class = "form-check">
                    <label for = "{{ item.id_for_label }}" > {{ item.choice_label }} </label>
                      {{ item.tag }}
                </div>
                  {% endfor %}
              <label > Ваши пожелания !</label>
              <div class = "mb-3"><textarea name="comment" cols="20" rows="5" class="form-control" id="id_comment"></textarea></div>
               <div class = "col"> <button class = "btn btn-dark ">
                    Подтвердить!
                </button>
               </div>
            </form>
          </div>
      </div>

  </div>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
 <script src="{% static 'bootstrap/css/bootstrap.min.js' %}"></script>
   <script src="https://api-maps.yandex.ru/2.1/?apikey=ваш API-ключ&lang=ru_RU" type="text/javascript"></script>
  </body>

<footer>
    <p>Бэк Django</p>
    <p> недофронт</p>
</footer>
<script type="text/javascript">
ymaps.ready(init);

function init() {
    var myMap = new ymaps.Map("map", {
            center: [62.033046, 129.732280],
            zoom: 12
        }, {
            searchControlProvider: 'yandex#search'
        }),

        myPieChart = new ymaps.Placemark([
            62.053777, 129.773393
        ], {

            data: [
                {weight: 8, color: '#0E4779'},
                {weight: 6, color: '#1E98FF'},
                {weight: 4, color: '#82CDFF'}
            ],
            iconCaption: "Место встречи"
        });

    myMap.geoObjects

        .add(myPieChart);
}

</script>
</html>

invites/templates/invites/index.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
  <body>


      <div id="headerwrap">
           <div class="container">
                <div class="col">
                    <h1> Красивый сайт</h1>
                    <h4> and </h4>
                    <h1> Красивый сайт</h1>
                </div>
                <div class="col">
                    <h3> Сентябрь</h3>
                    <h3> 17 </h3>
                    <h3> 2022</h3>
                </div>
            </div>
      </div>

      <div id="mainid">
       <div class="container">

                <h3> До события </h3>
                <div class="row" id = "data">
                    <p class = "col-3" > дни </p>
                   <p class = "col-3"> часы </p>
                    <p class = "col-3">минуты </p>
                   <p class = "col-3"> секунды </p>
                </div>

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/static/img/1.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item size">
      <img src="/static/img/2.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/static/img/3.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
 </div>
            <p>  sdsdsdssdsd sds dsdsd  </p>
           <hr>
           <h3>МЕСТО ПРОВЕДЕНИЯ</h3>
            <p>  sdsdsdssdsd sds dsdsd  </p>
           <h3>НАШИ ПОЖЕЛАНИЯ</h3>
           <hr>
           <p>qweqwewqe</p>
  </div>
   <h5 id = "wishesid" >Подтвердите свое присутствие:</h5>
  <div class="f" >
      <div class = "card">
          <div class="card-body">
                <label id = "name"> Ваше Имя</label>
              <div class = "mb-3"><input  class="form-control"> </div>
              <label id = "questionid"> Придете ли Вы на наш вечер?</label>
              <div class = "form-check">
                  <input type="radio" class = "form-check-input">
                  <label > Да</label>
                  </div>
              <div class="form-check">
                  <input type="radio" class = "form-check-input">
                  <label > Нет</label>
              </div>
              <label > Ваши пожелания !</label>
              <div class = "mb-3"><textarea name="" id="" cols="20" rows="5" class = form-control></textarea></div>
               <div class = "col"> <button class = "btn btn-dark ">
                    Подтвердить!
                </button>
               </div>
          </div>
      </div>
  </div>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
 <script src="{% static 'bootstrap/css/bootstrap.min.js' %}"></script>
  </body>

<footer>
    <p>Сайт создан на Django</p>
    <p>a фронт реализован Bootstrapоп</p>
</footer>
</html>

invites/templates/invites/invites_detail.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/invites_detail.css' %}">
  </head>
  <body>
   <div id="header">
      <div class="box">
                <div class="card shadow mb-5 bg-body rounded" >
                        <img src="/static/img/bgresult.jpg" alt="Наше фото">
                   {% if invites_item.is_confirm == True %}
                    <p id = "centered">Спасибо за ответ {{ invites_item.name }}!</p>
                    <p id = "bottomed">ждем вас в г. Якутск </p>
                    {% else %}
                     <p id = "centered">Спасибо за ответ {{ invites_item.name }}!</p>
                    <p id = "bottomed"> Сожелеем что вы не подойдете ...</p>
                    {% endif %}
                </div>
            </div>
      </div>
<hr>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
 <script src="{% static 'bootstrap/css/bootstrap.min.js' %}"></script>
</body>
</html>

invites/templates/invites/main.html
{% extends 'base.html' %}
{% block title %}
    {{ title }} :: {{ block.super }}

{% endblock %}


{% block content %}

{% for item in invites %}
<div class="card mb-3">
<div class="card-header">
</div>
    <div class="card-body">
        <div class="media">

            <div class="media-body">
                <h5 class="card-title"> {{ item.name }}</h5>
                <p class="card-title"> {{ item.comment|linebreaks|truncatewords:50 }}</p>
                <a href="{{ item.get_absolute_url }}" class="btn btn-primary"> Ссылка на новости</a>

            </div>
        </div>
         </div>
    <div class="card-footer text-muted">
        {{ item.created_at|date:"Y-m-d H:i"}}

    </div>
        {{ item.created_at|timesince}}
</div>
{% endfor %}

{% endblock %}